-- AlterTable
ALTER TABLE "Story" ADD COLUMN     "queryVersion" TEXT;

-- AlterTable
ALTER TABLE "TopicMemory" ADD COLUMN     "demandScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "velocityScore" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "winsLong" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "winsShort" DOUBLE PRECISION NOT NULL DEFAULT 0;
