import React, { useState, useEffect, useRef, useCallback } from "react";
import { useParams, Link } from "react-router-dom";
import { useChannelPath } from "@/hooks/useChannelPath";
import {
  ArrowLeft, ExternalLink, FileText, Globe, Languages, Brain,
  Sparkles, CheckCircle2, AlertTriangle, ChevronDown, ChevronRight,
  Copy, Check, Search, Target, Server, Cpu, ListOrdered, Users, Link2, Info,
  Loader2, RotateCcw, PenLine,
} from "lucide-react";
import { toast } from "sonner";
import { EmptyState } from "@/components/ui/empty-state";
import { FLOW_DEFS } from "@/constants/flowDefs";

/* ─── Types ─── */

interface QualityEval {
  score: number;
  issues?: string[] | null;
  filled?: number;
  total?: number;
  ratio?: number;
  arabicRatio?: number;
  chars?: number;
  citationCount?: number;
  narrativeStrength?: number | null;
}

interface DisplayBlockDef {
  type: string;
  label?: string;
  value?: string | number;
  variant?: string;
  text?: string;
  rows?: { label: string; value: number; weight: number }[];
  items?: { title: string; subtitle?: string }[];
  raw?: number;
  adjustments?: { label: string; value: number }[];
  final?: number;
  quality?: QualityEval;
}

interface LogEntry {
  step: string;
  stage?: string;
  label?: string;
  icon?: string;
  subtitle?: string;
  display?: DisplayBlockDef[];
  status?: string;
  processor?: "ai" | "api" | "server";
  service?: string;
  source?: string;
  chars?: number;
  threshold?: number;
  error?: string;
  reason?: string;
  detected?: string;
  model?: string;
  inputLang?: string;
  inputChars?: number;
  outputChars?: number;
  topic?: string;
  tags?: string[];
  sentiment?: string;
  contentType?: string;
  region?: string;
  relevance?: number;
  viralPotential?: number;
  freshness?: number;
  preferenceBias?: number;
  finalScore?: number;
  storyId?: string | null;
  at?: string;
  needed?: boolean;
  resultsCount?: number;
  titles?: string[];
  snippets?: string[];
  citations?: number;
  briefKeys?: string[];
  narrativeStrength?: number;
  hasBrief?: boolean;
  query?: string;
  matchCount?: number;
  topMatch?: string | null;
  embeddingInputChars?: number;
  inputTokens?: number | null;
  outputTokens?: number | null;
  totalTokens?: number | null;
  promptSent?: string;
  rawResponse?: string;
  contentPreview?: string;
  quality?: QualityEval;
  fieldsTranslated?: number;
  summary?: string;
  uniqueAngle?: string;
  isBreaking?: boolean;
  nicheScore?: number;
  nicheActive?: boolean;
  topicDemand?: number;
  topicDemandSimilarCount?: number;
  competitionPenalty?: number;
  similarCount?: number;
  avgPerformanceRatio?: number;
  tier?: number;
  dialect?: string;
  hasHooks?: boolean;
  hasResearch?: boolean;
  rawChars?: number;
  titlePreview?: string;
}

interface Analysis {
  topic?: string;
  topicAr?: string;
  tags?: string[];
  tagsAr?: string[];
  sentiment?: string;
  contentType?: string;
  region?: string;
  regionAr?: string;
  viralPotential?: number;
  relevance?: number;
  summary?: string;
  summaryAr?: string;
  isBreaking?: boolean;
  uniqueAngle?: string;
  uniqueAngleAr?: string;
  parseError?: boolean;
  raw?: string;
  research?: {
    relatedArticles?: { title?: string; url?: string; snippet?: string }[];
    backgroundContext?: string;
    citations?: string[];
    similarVideos?: { title?: string; views?: number; channel?: string; similarity?: number; type?: string }[];
    brief?: {
      whatHappened?: string;
      howItHappened?: string;
      whatWasTheResult?: string;
      keyFacts?: string[];
      timeline?: { date?: string; event?: string }[];
      mainCharacters?: { name?: string; role?: string }[];
      sources?: { title?: string; url?: string }[];
      competitionInsight?: string;
      suggestedHook?: string;
      narrativeStrength?: number;
    };
    researchedAt?: string;
  };
  draftScript?: {
    suggestedTitle?: string;
    script?: string;
    youtubeTags?: string[];
    scriptDuration?: number;
    scriptRaw?: string;
    autoGenerated?: boolean;
  };
}

interface ArticleDetail {
  id: string;
  channelId: string;
  url: string;
  title: string | null;
  description: string | null;
  content: string | null;
  contentClean: string | null;
  contentAr: string | null;
  contentRawLength: number;
  contentCleanLength: number;
  contentArLength: number;
  publishedAt: string | null;
  language: string | null;
  stage: string;
  status: string;
  retries: number;
  error: string | null;
  startedAt: string | null;
  finishedAt: string | null;
  processingLog: LogEntry[] | null;
  analysis: Analysis | null;
  relevanceScore: number | null;
  finalScore: number | null;
  rankReason: string | null;
  storyId: string | null;
  source: { id: string; label: string; type: string; language: string } | null;
  createdAt: string;
  updatedAt: string;
}

/* ─── Timeline stage definitions (aligned with Pipeline mother flows) ─── */

interface TimelineStage {
  id: string;
  label: string;
  icon: typeof FileText;
  color: string;
  bgColor: string;
}

/** Timeline uses the 8 flow definitions (Imported, Content, Classify, Research, Synthesis, Translation, Score, Promote). */
const TIMELINE_STAGES: TimelineStage[] = FLOW_DEFS.map((f) => ({
  id: f.id,
  label: f.name,
  icon: f.icon,
  color: f.color,
  bgColor: f.bgColor,
}));

const STAGE_ORDER = ["imported", "content", "classify", "research", "translated", "script", "score", "done"];

function stageIndex(stage: string): number {
  const idx = STAGE_ORDER.indexOf(stage);
  return idx === -1 ? 0 : idx;
}

/* ─── Helpers ─── */

function fmtDate(d: string | null): string {
  if (!d) return "—";
  return new Date(d).toLocaleString("en-US", {
    month: "short", day: "numeric", year: "numeric",
    hour: "2-digit", minute: "2-digit", second: "2-digit",
  });
}

function fmtElapsed(from: string | null, to?: string | null): string {
  if (!from) return "";
  const start = new Date(from).getTime();
  const end = to ? new Date(to).getTime() : Date.now();
  const ms = end - start;
  if (ms < 0) return "";
  const totalSeconds = Math.floor(ms / 1000);
  if (totalSeconds < 60) return `${totalSeconds}s`;
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  if (minutes < 60) return `${minutes}m ${seconds}s`;
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  return `${hours}h ${mins}m`;
}

function extractDomain(url: string): string {
  try { return new URL(url).hostname.replace(/^www\./, ""); } catch { return ""; }
}

/* ─── Main Component ─── */

export default function ArticleDetailPage() {
  const { channelId, id } = useParams();
  const pp = useChannelPath();
  const [article, setArticle] = useState<ArticleDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [restarting, setRestarting] = useState(false);

  const fetchArticle = useCallback((silent = false) => {
    if (!id) return;
    if (!silent) setLoading(true);
    fetch(`/api/article-pipeline/${id}/detail`, { credentials: "include" })
      .then((r) => { if (!r.ok) throw new Error("Not found"); return r.json(); })
      .then((d) => setArticle(d))
      .catch((e) => { if (!silent) setError(e.message); })
      .finally(() => { if (!silent) setLoading(false); });
  }, [id]);

  useEffect(() => { fetchArticle(); }, [fetchArticle]);

  const TERMINAL_STATES = useRef(new Set(["done", "failed", "review"]));
  const isProcessing = article != null
    && !TERMINAL_STATES.current.has(article.stage)
    && !TERMINAL_STATES.current.has(article.status);

  useEffect(() => {
    if (!isProcessing || !id) return;

    const es = new EventSource(`/api/article-pipeline/${id}/events`, { withCredentials: true });
    let fallbackTimer: ReturnType<typeof setInterval> | null = null;

    es.onmessage = () => fetchArticle(true);

    es.onerror = () => {
      es.close();
      if (!fallbackTimer) {
        fallbackTimer = setInterval(() => fetchArticle(true), 5000);
      }
    };

    return () => {
      es.close();
      if (fallbackTimer) clearInterval(fallbackTimer);
    };
  }, [isProcessing, id, fetchArticle]);

  const handleRestart = async (stage?: string) => {
    if (!id || restarting) return;
    setRestarting(true);
    try {
      const res = await fetch(`/api/article-pipeline/${id}/restart`, {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(stage ? { stage } : {}),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Restart failed");
      toast.success(`Restarting from "${data.stage}" stage`);
      fetchArticle();
    } catch (e: any) {
      toast.error(e.message);
    } finally {
      setRestarting(false);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  if (error || !article) {
    return (
      <div className="flex flex-col items-center justify-center h-screen gap-3">
        <AlertTriangle className="w-8 h-8 text-destructive" />
        <p className="text-[13px] text-muted-foreground">{error || "Article not found"}</p>
        <Link to={pp("/article-pipeline")} className="text-[12px] text-primary hover:underline">
          Back to Pipeline
        </Link>
      </div>
    );
  }

  const log: LogEntry[] = Array.isArray(article.processingLog) ? article.processingLog : [];
  const currentStageIdx = stageIndex(article.stage);
  const isDone = article.stage === "done";
  const isFailed = article.stage === "failed";

  return (
    <div className="flex flex-col min-h-screen">
      {/* Top bar */}
      <div className="h-12 flex items-center gap-3 px-6 border-b border-border shrink-0 max-lg:px-4">
        <Link to={pp("/article-pipeline")} className="text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="w-4 h-4" />
        </Link>
        <h1 className="text-sm font-semibold text-foreground truncate">Article Inspector</h1>
        <span className={`ml-auto inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[11px] font-semibold ${
          isDone ? "bg-success/15 text-success" :
          isFailed ? "bg-destructive/15 text-destructive" :
          article.status === "review" ? "bg-orange/15 text-orange" :
          "bg-primary/15 text-primary"
        }`}>
          {isDone ? "Completed" : isFailed ? "Failed" : article.status === "review" ? "Review" : article.stage}
        </span>
      </div>

      <div className="flex-1 overflow-auto">
        <div className="max-w-4xl mx-auto px-6 py-6 max-lg:px-4">

          {/* Article header card */}
          <div className="rounded-lg border border-border bg-card p-5 mb-6">
            <div className="flex items-start justify-between gap-3 mb-3">
              <h2 className="text-[16px] font-semibold text-foreground leading-snug" dir="auto">
                {article.title || "Untitled"}
              </h2>
              <a href={article.url} target="_blank" rel="noopener noreferrer"
                className="shrink-0 p-1.5 rounded-lg border border-border hover:bg-card transition-colors">
                <ExternalLink className="w-3.5 h-3.5 text-muted-foreground" />
              </a>
            </div>
            {article.description && (
              <p className="text-[12px] text-muted-foreground leading-relaxed mb-3 line-clamp-2" dir="auto">
                {article.description}
              </p>
            )}
            <div className="flex flex-wrap items-center gap-3 text-[11px] font-mono text-muted-foreground">
              <span>{extractDomain(article.url)}</span>
              {article.source && <span className="px-1.5 py-0.5 rounded bg-card text-foreground/70">{article.source.label}</span>}
              {article.language && (
                <span className={`px-1.5 py-0.5 rounded font-bold ${
                  article.language === "ar" ? "bg-success/15 text-success" : "bg-primary/15 text-primary"
                }`}>{article.language.toUpperCase()}</span>
              )}
              {article.publishedAt && <span>Published: {fmtDate(article.publishedAt)}</span>}
              <span>Created: {fmtDate(article.createdAt)}</span>
              {article.startedAt && <span>Started: {fmtDate(article.startedAt)}</span>}
              {article.finishedAt && (
                <span>Finished: {fmtDate(article.finishedAt)} ({fmtElapsed(article.startedAt, article.finishedAt)})</span>
              )}
              {article.retries > 0 && <span className="text-orange">{article.retries} retries</span>}
            </div>
            {article.error && (
              <div className="mt-3 px-3 py-2 rounded-lg bg-destructive/10 text-destructive text-[11px] font-mono">
                {article.error}
              </div>
            )}
            {article.status !== "running" && (
              <RestartControl
                stage={article.stage}
                restarting={restarting}
                onRestart={handleRestart}
              />
            )}
            {article.finalScore != null && (
              <div className="mt-3 flex items-center gap-4 text-[11px] font-mono">
                <span className="text-foreground font-semibold">Score: {article.finalScore.toFixed(2)}</span>
                <span className="text-muted-foreground">→ {(Math.round(article.finalScore * 10 * 10) / 10).toFixed(1)}/10</span>
                {article.relevanceScore != null && <span className="text-muted-foreground">Relevance: {article.relevanceScore.toFixed(2)}</span>}
                {article.rankReason && <span className="text-muted-foreground">{article.rankReason}</span>}
              </div>
            )}
            {article.storyId && (
              <div className="mt-3">
                <Link to={pp(`/story/${article.storyId}`)}
                  className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-success/10 text-success text-[11px] font-semibold hover:bg-success/20 transition-colors">
                  <CheckCircle2 className="w-3 h-3" /> View Story
                </Link>
              </div>
            )}
          </div>

          {/* Stage detail sections */}
          <div className="space-y-4">
            {TIMELINE_STAGES.map((stage) => {
              const mappedStage = stage.id === "promote" ? null : stage.id === "synthesis" ? "research" : stage.id;

              let stageState: "completed" | "active" | "waiting";
              if (stage.id === "promote") {
                stageState = isDone ? "completed" : "waiting";
              } else if (mappedStage != null) {
                const mappedIdx = stageIndex(mappedStage);
                if (isDone || currentStageIdx > mappedIdx) {
                  stageState = "completed";
                } else if (currentStageIdx === mappedIdx) {
                  stageState = isFailed || article.status === "review" ? "completed" : "active";
                } else {
                  stageState = "waiting";
                }
              } else {
                stageState = "waiting";
              }

              return (
                <StageSection
                  key={stage.id}
                  stage={stage}
                  stageState={stageState}
                  article={article}
                  log={log}
                  pp={pp}
                />
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}

/* ─── Restart Control ─── */

const RESTARTABLE_STAGES = [
  { id: "imported", label: "Imported" },
  { id: "content", label: "Content" },
  { id: "classify", label: "Classify" },
  { id: "research", label: "Research" },
  { id: "translated", label: "Translation" },
  { id: "script", label: "Script" },
  { id: "score", label: "Score" },
];

function RestartControl({
  stage,
  restarting,
  onRestart,
}: {
  stage: string;
  restarting: boolean;
  onRestart: (stage?: string) => void;
}) {
  const [showPicker, setShowPicker] = useState(false);
  const currentIdx = RESTARTABLE_STAGES.findIndex((s) => s.id === stage);
  const canRestartCurrent = currentIdx !== -1 || stage === "done" || stage === "failed";

  return (
    <div className="mt-3 flex items-center gap-2">
      <button
        onClick={() => onRestart()}
        disabled={restarting || !canRestartCurrent}
        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-border bg-card hover:bg-card/80 text-[11px] font-semibold text-foreground transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
      >
        <RotateCcw className={`w-3 h-3 ${restarting ? "animate-spin" : ""}`} />
        {restarting ? "Restarting…" : "Restart"}
      </button>
      <div className="relative">
        <button
          onClick={() => setShowPicker(!showPicker)}
          className="inline-flex items-center gap-1 px-2 py-1.5 rounded-lg border border-border bg-card hover:bg-card/80 text-[10px] font-mono text-muted-foreground transition-colors"
        >
          from stage
          <ChevronDown className="w-3 h-3" />
        </button>
        {showPicker && (
          <div className="absolute top-full left-0 mt-1 z-50 min-w-[140px] rounded-lg border border-border bg-card shadow-lg py-1">
            {RESTARTABLE_STAGES.map((s) => (
              <button
                key={s.id}
                onClick={() => { setShowPicker(false); onRestart(s.id); }}
                disabled={restarting}
                className="w-full text-left px-3 py-1.5 text-[11px] font-mono text-foreground hover:bg-card transition-colors disabled:opacity-40"
              >
                {s.label}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

/* ─── Stage Section (flat collapsible card — no timeline dots/lines) ─── */

function StageSection({
  stage, stageState, article, log, pp,
}: {
  stage: TimelineStage;
  stageState: "completed" | "active" | "waiting";
  article: ArticleDetail;
  log: LogEntry[];
  pp: (p: string) => string;
}) {
  const [expanded, setExpanded] = useState(stageState !== "waiting");
  const Icon = stage.icon;
  const stepLog = getStepLogs(stage.id, log);
  const timestamp = stepLog.length > 0 ? stepLog[0].at : null;
  const isWaiting = stageState === "waiting";
  const isActive = stageState === "active";

  return (
    <div className={`rounded-lg border overflow-hidden ${
      isWaiting ? "border-border/50 bg-card/60" : "border-border bg-card"
    }`}>
      <button
        onClick={() => !isWaiting && setExpanded(!expanded)}
        className={`flex items-center gap-2.5 w-full text-left px-4 py-3 transition-colors ${
          isWaiting ? "cursor-default" : "hover:bg-card/50"
        }`}
      >
        {isActive ? (
          <Loader2 className={`w-4 h-4 ${stage.color} shrink-0 animate-spin`} />
        ) : (
          <Icon className={`w-4 h-4 ${isWaiting ? "text-muted-foreground" : stage.color} shrink-0`} />
        )}
        <span className={`text-[13px] font-semibold ${isWaiting ? "text-muted-foreground" : "text-foreground"}`}>
          {stage.label}
        </span>
        {isActive && (
          <span className="text-[10px] font-mono text-primary px-1.5 py-0.5 rounded bg-primary/10">Processing…</span>
        )}
        {isWaiting && (
          <span className="text-[10px] font-mono text-muted-foreground px-1.5 py-0.5 rounded bg-card">Waiting</span>
        )}
        {timestamp && <span className="text-[10px] text-muted-foreground font-mono">{fmtDate(timestamp)}</span>}
        {!isWaiting && (
          expanded
            ? <ChevronDown className="w-3.5 h-3.5 text-muted-foreground ml-auto" />
            : <ChevronRight className="w-3.5 h-3.5 text-muted-foreground ml-auto" />
        )}
      </button>
      {expanded && !isWaiting && (
        <>
          {stage.id === "imported" && <ImportedDetail article={article} log={log} />}
          {stage.id === "content" && <ContentDetail article={article} log={log} />}
          {stage.id === "classify" && <AiAnalysisDetail article={article} log={log} />}
          {stage.id === "research" && <ResearchDetail article={article} log={log} pp={pp} />}
          {stage.id === "translated" && <TranslatedDetail article={article} log={log} />}
          {stage.id === "synthesis" && <SynthesisDetail article={article} log={log} />}
          {stage.id === "script" && <ScriptDetail article={article} log={log} />}
          {stage.id === "score" && <ScoringDetail article={article} log={log} />}
          {stage.id === "promote" && <PromoteDetail article={article} log={log} pp={pp} />}
          <UnknownEntries stageId={stage.id} log={log} />
        </>
      )}
    </div>
  );
}

/* ─── Step log helpers ─── */

/** Step order and ids per stage — must match Article Pipeline Kanban exactly. */
const STEP_MAP: Record<string, string[]> = {
  imported: ["imported"],
  content: ["apify_content", "firecrawl", "html_fetch", "title_desc"],
  classify: ["classify"],
  research: ["research_decision", "firecrawl_search", "perplexity_context"],
  synthesis: ["synthesis", "research"],
  translated: ["detect_language", "translate_content", "translate_analysis", "translate_research"],
  script: ["auto_script"],
  score: ["score_similarity", "score_topic_demand", "score_niche", "score_ai_analysis", "score"],
  promote: ["promote"],
};

function getStepLogs(stageId: string, log: LogEntry[]): LogEntry[] {
  const byStage = log.filter((e) => e.stage === stageId);
  if (byStage.length > 0) return byStage;
  const steps = STEP_MAP[stageId] || [];
  return log.filter((e) => steps.includes(e.step));
}

/** Step id → label, subtitle, icon (matches Pipeline Kanban columns exactly). */
const STEP_DISPLAY: Record<string, { label: string; subtitle?: string; icon: typeof FileText }> = {
  imported: { label: "Imported", subtitle: "Queued for ingestion", icon: FileText },
  apify_content: { label: "Apify Content", subtitle: "Article body from Apify actor", icon: FileText },
  firecrawl: { label: "Firecrawl", subtitle: "Scraped via Firecrawl API", icon: Globe },
  html_fetch: { label: "HTML Fetch", subtitle: "Fallback HTML fetch", icon: Globe },
  content_source: { label: "Content Source", icon: CheckCircle2 },
  title_desc: { label: "Title+Desc", subtitle: "Title and description only", icon: FileText },
  classify: { label: "Classified", subtitle: "Topic, tags, region, sentiment", icon: Brain },
  research_decision: { label: "Decision", subtitle: "Whether research is needed", icon: Target },
  firecrawl_search: { label: "Web Search", subtitle: "Related articles via search", icon: Search },
  perplexity_context: { label: "Background", subtitle: "Context from Perplexity", icon: Globe },
  synthesis: { label: "Synthesis", subtitle: "AI brief (hook, narrative, facts)", icon: Brain },
  research: { label: "Research Complete", subtitle: "Research stage done", icon: Search },
  detect_language: { label: "Language", subtitle: "Detect source language", icon: Languages },
  translate_content: { label: "Translate Content", subtitle: "Article text → Arabic", icon: Languages },
  translate_analysis: { label: "Translate Fields", subtitle: "Classification fields → Arabic", icon: Brain },
  translate_research: { label: "Translate Brief", subtitle: "Research brief → Arabic", icon: Search },
  score_similarity: { label: "Competition Match", subtitle: "Match vs. existing stories", icon: Target },
  score_topic_demand: { label: "Topic Demand", subtitle: "Competitor audience engagement", icon: Users },
  score_niche: { label: "Niche Fit", subtitle: "Channel niche relevance", icon: Target },
  score_ai_analysis: { label: "AI Scoring", subtitle: "Relevance & viral scores", icon: Brain },
  score: { label: "Final Score", subtitle: "Composite score", icon: Sparkles },
  promote: { label: "Story Created", subtitle: "Create or link story", icon: CheckCircle2 },
  auto_script: { label: "Draft Script", subtitle: "Auto-generated script with branded hooks", icon: PenLine },
};

/** Single card for one pipeline step — matches Kanban column (title + optional subtitle). */
function LogStepCard({
  entry,
  stepId,
  label,
  subtitle,
  icon: Icon,
  children,
  skippedReason,
}: {
  entry: LogEntry | null;
  stepId: string;
  label: string;
  subtitle?: string;
  icon: typeof FileText;
  children: React.ReactNode;
  skippedReason?: string;
}) {
  const [showDetails, setShowDetails] = useState(false);
  const skipped = !entry && skippedReason;
  const hasEntry = !!entry;
  const detailsContent = entry && (
    entry.error
      ? entry.error
      : entry.reason
        ? entry.reason
        : (entry as any).rawResponse
          ? String((entry as any).rawResponse).slice(0, 1000)
          : entry.status
            ? `Status: ${entry.status}`
            : null
  );

  return (
    <div className={`px-3 py-2.5 rounded-lg border space-y-2 ${skipped ? "bg-card/20 border-border/50 opacity-60" : "bg-card/50 border-border"}`}>
      <div className="flex items-center justify-between flex-wrap gap-2">
        <div className="flex flex-col gap-0.5">
          <div className="flex items-center gap-2 flex-wrap">
            {Icon && <Icon className="w-3.5 h-3.5 text-muted-foreground shrink-0" />}
            <span className="text-[11px] font-semibold">{label}</span>
            {entry?.processor && <ProcessorBadge type={entry.processor} />}
            {entry?.service && <span className="text-[9px] font-mono text-muted-foreground">{entry.service}</span>}
            {entry?.status && <StatusBadge status={entry.status} />}
            {hasEntry && (
              <button
                type="button"
                onClick={() => setShowDetails((v) => !v)}
                className="inline-flex items-center justify-center w-5 h-5 rounded-full text-muted-foreground hover:text-foreground hover:bg-card transition-colors"
                title="Show details"
                aria-label="Show status details"
              >
                <Info className="w-3.5 h-3.5" />
              </button>
            )}
            {skipped && <span className="text-[9px] font-mono text-muted-foreground px-1.5 py-0.5 rounded bg-card">skipped</span>}
          </div>
          {subtitle && <div className="text-[10px] text-muted-foreground font-mono leading-tight pl-5.5">{subtitle}</div>}
        </div>
        {entry && (entry.inputTokens != null || entry.outputTokens != null) && (
          <TokensBadge entry={entry} />
        )}
      </div>
      {showDetails && detailsContent && (
        <div className={`mt-2 px-2.5 py-2 rounded-lg text-[11px] font-mono whitespace-pre-wrap break-words max-h-40 overflow-y-auto border ${
          entry?.status === "failed" || entry?.status === "parse_error"
            ? "bg-destructive/10 border-destructive/20 text-destructive"
            : "bg-card border-border text-muted-foreground"
        }`}>
          {typeof detailsContent === "string" ? detailsContent : JSON.stringify(detailsContent).slice(0, 500)}
        </div>
      )}
      {skipped && <div className="text-[11px] text-muted-foreground">{skippedReason}</div>}
      {!skipped && children && <div className="text-[12px] text-muted-foreground leading-relaxed">{children}</div>}
    </div>
  );
}

/** Result output card — no processor/status/tokens; for grouped result sections. */
function ResultCard({
  label,
  icon: Icon,
  children,
}: {
  label: string;
  icon: typeof FileText;
  children: React.ReactNode;
}) {
  return (
    <div className="px-3 py-2.5 rounded-lg border border-border/80 bg-card/80 space-y-2">
      <div className="flex items-center gap-2">
        {Icon && <Icon className="w-3.5 h-3.5 text-muted-foreground" />}
        <span className="text-[11px] font-semibold text-foreground">{label}</span>
      </div>
      {children && <div className="text-[12px] text-muted-foreground leading-relaxed">{children}</div>}
    </div>
  );
}

/* ─── Collapsible content block ─── */

function ContentBlock({ label, content, dir, maxHeight = 200 }: {
  label: string; content: string | null; dir?: string; maxHeight?: number;
}) {
  const [expanded, setExpanded] = useState(false);
  const [copied, setCopied] = useState(false);

  if (!content) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <div className="border border-border rounded-lg overflow-hidden">
      <div className="flex items-center justify-between px-3 py-2 bg-card/50 border-b border-border">
        <span className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider">{label}</span>
        <div className="flex items-center gap-2">
          <span className="text-[10px] font-mono text-muted-foreground">{content.length.toLocaleString()} chars</span>
          <button onClick={handleCopy} className="text-muted-foreground hover:text-foreground transition-colors">
            {copied ? <Check className="w-3 h-3 text-success" /> : <Copy className="w-3 h-3" />}
          </button>
        </div>
      </div>
      <div
        className="px-3 py-2.5 text-[12px] text-foreground/80 leading-[1.9] overflow-hidden transition-all"
        style={{ maxHeight: expanded ? "none" : maxHeight }}
        dir={dir || "auto"}
      >
        {content.split(/\n\n+/).map((para, i) => (
          <p key={i} className="mb-3 last:mb-0 whitespace-pre-wrap">
            {para}
          </p>
        ))}
      </div>
      {content.length > 300 && (
        <button
          onClick={() => setExpanded(!expanded)}
          className="w-full px-3 py-1.5 text-[10px] font-mono text-primary hover:text-foreground bg-card/30 border-t border-border transition-colors"
        >
          {expanded ? "Show less" : "Show more"}
        </button>
      )}
    </div>
  );
}

/* ─── Side by side content comparison ─── */

function ContentComparison({ left, right, leftLabel, rightLabel, leftDir, rightDir }: {
  left: string | null; right: string | null;
  leftLabel: string; rightLabel: string;
  leftDir?: string; rightDir?: string;
}) {
  if (!left && !right) return null;

  return (
    <div className="grid grid-cols-2 gap-3 max-lg:grid-cols-1">
      <ContentBlock label={leftLabel} content={left} dir={leftDir} />
      <ContentBlock label={rightLabel} content={right} dir={rightDir} />
    </div>
  );
}

/* ─── Status badge (color-coded to match pipeline semantics) ─── */

const STATUS_BADGE_COLORS: Record<string, string> = {
  ok: "bg-success/10 text-success",
  created: "bg-success/10 text-success",
  linked: "bg-success/10 text-success",
  skipped: "bg-destructive/10 text-destructive",
  failed: "bg-destructive/10 text-destructive",
  parse_error: "bg-destructive/10 text-destructive",
  review: "bg-orange/10 text-orange",
  partial: "bg-orange/10 text-orange",
  empty: "bg-dim/10 text-muted-foreground",
};

function StatusBadge({ status, label }: { status?: string; label?: string }) {
  const text = label || status || "unknown";
  const color = (status && STATUS_BADGE_COLORS[status]) || "bg-dim/10 text-muted-foreground";

  return (
    <span className={`inline-flex items-center px-2 py-0.5 rounded text-[10px] font-mono font-semibold ${color}`}>
      {text}
    </span>
  );
}

function ProcessorBadge({ type }: { type: "ai" | "server" | "api" }) {
  if (type === "ai") return (
    <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-purple/10 text-foreground text-[9px] font-mono font-bold uppercase">
      <Cpu className="w-2.5 h-2.5" />AI
    </span>
  );
  if (type === "api") return (
    <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-primary/10 text-foreground text-[9px] font-mono font-bold uppercase">
      <Globe className="w-2.5 h-2.5" />API
    </span>
  );
  return (
    <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-dim/10 text-foreground text-[9px] font-mono font-bold uppercase">
      <Server className="w-2.5 h-2.5" />Server
    </span>
  );
}

function TokensBadge({ entry }: { entry?: LogEntry | null }) {
  if (!entry?.totalTokens) return null;
  return (
    <span className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded bg-card border border-border text-[10px] font-mono text-muted-foreground">
      <span>↑{entry.inputTokens?.toLocaleString()}</span>
      <span>↓{entry.outputTokens?.toLocaleString()}</span>
      <span className="text-foreground font-semibold">Σ{entry.totalTokens.toLocaleString()}</span>
    </span>
  );
}

function ExpandableText({ label, text, maxLen }: { label: string; text: string; maxLen?: number }) {
  const [open, setOpen] = useState(false);
  const isTruncated = maxLen && text.length >= maxLen - 2;
  return (
    <div>
      <button onClick={() => setOpen(!open)}
        className="text-[10px] font-mono text-primary hover:text-primary/80 transition-colors flex items-center gap-1">
        {open ? "▾ Hide" : "▸ Show"} {label}
      </button>
      {open && (
        <div className="mt-1.5 px-3 py-2 rounded-lg bg-card/50 border border-border text-[11px] font-mono text-muted-foreground whitespace-pre-wrap leading-relaxed max-h-64 overflow-y-auto break-all">
          {text}
          {isTruncated && <span className="text-primary">…(truncated)</span>}
        </div>
      )}
    </div>
  );
}

/* ─── Icon map for self-describing entries ─── */

const ICON_MAP: Record<string, typeof FileText> = {
  "file-text": FileText, "globe": Globe, "brain": Brain, "search": Search,
  "target": Target, "languages": Languages, "sparkles": Sparkles,
  "check-circle": CheckCircle2, "users": Users, "pen-line": PenLine,
  "download": ArrowLeft, "server": Server, "cpu": Cpu, "info": Info,
};

function resolveIcon(iconKey?: string): typeof FileText {
  if (!iconKey) return FileText;
  return ICON_MAP[iconKey] || FileText;
}

/* ─── Display block renderer — renders self-describing UI primitives from backend ─── */

function DisplayBlockList({ blocks }: { blocks: DisplayBlockDef[] }) {
  return (
    <div className="space-y-2">
      {blocks.map((block, i) => (
        <DisplayBlockItem key={i} block={block} />
      ))}
    </div>
  );
}

function DisplayBlockItem({ block }: { block: DisplayBlockDef }) {
  switch (block.type) {
    case "text":
      return <span>{String(block.value ?? "")}</span>;

    case "stat":
      return (
        <div className="flex items-center gap-2 text-[11px]">
          <span className="text-muted-foreground">{block.label}:</span>
          <span className="text-foreground font-medium">{String(block.value ?? "—")}</span>
        </div>
      );

    case "gauge":
      return <ScoreGauge label={block.label ?? ""} value={typeof block.value === "number" ? block.value : 0} />;

    case "badge": {
      const BADGE_COLORS: Record<string, string> = {
        success: "bg-success/10 text-success",
        primary: "bg-primary/10 text-primary",
        muted: "bg-dim/10 text-muted-foreground",
      };
      const color = BADGE_COLORS[block.variant ?? "muted"] || BADGE_COLORS.muted;
      return (
        <span className={`inline-flex items-center px-2 py-0.5 rounded text-[10px] font-mono font-semibold ${color}`}>
          {block.label}
        </span>
      );
    }

    case "breakdown":
      if (!block.rows || !Array.isArray(block.rows)) return null;
      return (
        <div className="space-y-1">
          {block.rows.map((row, i) => (
            <ScoreRow
              key={i}
              label={row.label}
              value={row.value}
              weight={row.weight}
              result={Math.round(row.value * row.weight * 1000) / 1000}
            />
          ))}
        </div>
      );

    case "formula": {
      const rawVal = typeof block.raw === "number" ? block.raw : 0;
      const adjustments = block.adjustments ?? [];
      const finalVal = typeof block.final === "number" ? block.final : 0;
      return (
        <div className="text-[11px] font-mono mt-1">
          Raw {rawVal.toFixed(3)}
          {adjustments.map((adj, i) => (
            <span key={i}> · {adj.label} {adj.value > 0 ? "+" : ""}{adj.value.toFixed(2)}</span>
          ))}
          {" → "}<span className="font-bold text-success">Final {finalVal.toFixed(2)}</span>
        </div>
      );
    }

    case "list":
      if (!block.items || !Array.isArray(block.items)) return null;
      return (
        <ul className="list-disc list-inside text-[11px] space-y-0.5">
          {block.items.map((item, i) => (
            <li key={i}>
              {item.title}
              {item.subtitle && <span className="text-muted-foreground ml-1">({item.subtitle})</span>}
            </li>
          ))}
        </ul>
      );

    case "expandable":
      if (!block.text) return null;
      return <ExpandableText label={block.label ?? "Details"} text={block.text} maxLen={1500} />;

    case "quality":
      return <QualityBadge quality={block.quality} />;

    default:
      return null;
  }
}

function QualityBadge({ quality }: { quality?: QualityEval | null }) {
  if (!quality) return null;
  const s = quality.score;
  const color = s >= 8 ? "bg-success/10 text-success" : s >= 5 ? "bg-orange/10 text-orange" : "bg-destructive/10 text-destructive";
  const label = s >= 8 ? "Good" : s >= 5 ? "Fair" : "Poor";
  return (
    <div className="space-y-1">
      <div className="flex items-center gap-2">
        <span className={`inline-flex items-center px-2 py-0.5 rounded text-[10px] font-mono font-bold ${color}`}>
          Quality: {label} ({s}/10)
        </span>
        {quality.filled != null && quality.total != null && (
          <span className="text-[10px] font-mono text-muted-foreground">{quality.filled}/{quality.total} fields</span>
        )}
      </div>
      {quality.issues && quality.issues.length > 0 && (
        <div className="flex flex-wrap gap-1">
          {quality.issues.map((issue, i) => (
            <span key={i} className="px-1.5 py-0.5 rounded bg-destructive/5 text-destructive text-[9px] font-mono">
              {issue}
            </span>
          ))}
        </div>
      )}
    </div>
  );
}

function StepHeader({ entry, label, icon: Icon }: { entry: LogEntry; label: string; icon?: typeof FileText }) {
  return (
    <div className="flex items-center justify-between flex-wrap gap-2">
      <div className="flex items-center gap-2">
        {Icon && <Icon className="w-3.5 h-3.5 text-muted-foreground" />}
        <span className="text-[11px] font-semibold">{label}</span>
        {entry.processor && <ProcessorBadge type={entry.processor} />}
        {entry.service && <span className="text-[9px] font-mono text-muted-foreground">{entry.service}</span>}
        {entry.status && <StatusBadge status={entry.status} />}
      </div>
      <div className="flex items-center gap-2">
        <TokensBadge entry={entry} />
      </div>
    </div>
  );
}

/* ─── Generic fallback for entries the stage detail components don't know about ─── */

function UnknownEntries({ stageId, log }: { stageId: string; log: LogEntry[] }) {
  const knownSteps = STEP_MAP[stageId] || [];
  const unknowns = log.filter(
    (e) => e.stage === stageId && !knownSteps.includes(e.step)
  );
  if (unknowns.length === 0) return null;

  return (
    <div className="px-4 pb-4 space-y-3">
      {unknowns.map((entry) => {
        const entryIcon = resolveIcon(entry.icon);
        const hasDisplay = entry.display && Array.isArray(entry.display) && entry.display.length > 0;
        return (
          <LogStepCard
            key={entry.step}
            entry={entry}
            stepId={entry.step}
            label={entry.label ?? entry.step}
            subtitle={entry.subtitle}
            icon={entryIcon}
          >
            {hasDisplay ? (
              <DisplayBlockList blocks={entry.display!} />
            ) : (
              <>
                {entry.reason && <span className="text-muted-foreground">{entry.reason}</span>}
                {entry.error && <span className="text-destructive">{entry.error}</span>}
                {entry.promptSent && <div className="mt-1"><ExpandableText label="prompt" text={entry.promptSent} maxLen={500} /></div>}
                {entry.rawResponse && <div className="mt-1"><ExpandableText label="response" text={entry.rawResponse} maxLen={500} /></div>}
              </>
            )}
          </LogStepCard>
        );
      })}
    </div>
  );
}

/* ─── Stage detail components ─── */

function ImportedDetail({ article, log }: { article: ArticleDetail; log: LogEntry[] }) {
  const stepId = "imported";
  const entry = log.find((e) => e.step === stepId);
  const { label, icon } = STEP_DISPLAY[stepId] || { label: stepId, icon: FileText };

  return (
    <div className="p-4 space-y-4">
      <LogStepCard entry={entry ?? null} stepId={stepId} label={label} subtitle={STEP_DISPLAY[stepId]?.subtitle} icon={icon}>
        {article.source && (
          <span>Source: <span className="text-foreground">{article.source.label}</span> ({article.source.type})</span>
        )}
        {article.source?.language && (
          <span className="ml-2">Language: <span className="text-foreground">{article.source.language.toUpperCase()}</span></span>
        )}
        {entry?.rawChars != null && <span className="block mt-1">{entry.rawChars.toLocaleString()} chars · {entry.titlePreview ? "title present" : ""}</span>}
      </LogStepCard>
      <ResultCard label="Source Content" icon={FileText}>
        {article.title && (
          <div className="mb-2">
            <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1">Title</div>
            <div className="text-[13px] text-foreground font-medium" dir="auto">{article.title}</div>
          </div>
        )}
        {article.description && (
          <div className="mb-2">
            <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1">Description</div>
            <div className="text-[12px] text-foreground/80" dir="auto">{article.description}</div>
          </div>
        )}
        <ContentBlock label={`Raw Content (${article.contentRawLength.toLocaleString()} chars)`} content={article.content} />
      </ResultCard>
    </div>
  );
}

function ContentDetail({ article, log }: { article: ArticleDetail; log: LogEntry[] }) {
  const steps = STEP_MAP.content;
  const apifyLog = log.find((e) => e.step === "apify_content");
  const apifySufficient = apifyLog && apifyLog.chars != null && apifyLog.threshold != null && apifyLog.chars >= apifyLog.threshold;
  const contentSourceLog = log.find((e) => e.step === "content_source");

  const getEntry = (stepId: string): LogEntry | null => {
    if (stepId === "title_desc") {
      return contentSourceLog?.source === "title_desc_fallback" ? contentSourceLog : null;
    }
    return log.find((e) => e.step === stepId) ?? null;
  };

  return (
    <div className="p-4 space-y-3">
      {steps.map((stepId) => {
        const entry = getEntry(stepId);
        const { label, subtitle, icon } = STEP_DISPLAY[stepId] || { label: stepId, icon: FileText };
        let body: React.ReactNode = null;
        if (stepId === "apify_content" && entry) {
          body = <>{entry.chars?.toLocaleString()} chars / {entry.threshold?.toLocaleString()} needed · {apifySufficient ? "Sufficient" : "Too short"}</>;
        } else if (stepId === "firecrawl" && entry) {
          body = <>{entry.chars != null && <span>{entry.chars.toLocaleString()} chars</span>}{entry.error && <span className="text-destructive"> · {entry.error}</span>}{entry.reason && <span> · {entry.reason}</span>}</>;
        } else if (stepId === "html_fetch" && entry) {
          body = <>{entry.chars != null && <span>{entry.chars.toLocaleString()} chars</span>}{entry.error && <span className="text-destructive"> · {entry.error}</span>}</>;
        } else if (stepId === "title_desc" && entry) {
          body = <>{entry.chars != null && <span>{entry.chars.toLocaleString()} chars</span>}{entry.reason && <span> · {entry.reason}</span>}</>;
        }
        let skippedReason: string | undefined;
        if (!entry) {
          if ((stepId === "firecrawl" || stepId === "html_fetch") && apifySufficient) {
            skippedReason = "Apify content was sufficient";
          } else if (stepId === "html_fetch" && log.find((e) => e.step === "firecrawl")?.status === "ok") {
            skippedReason = "Firecrawl content was sufficient";
          } else if (stepId === "title_desc") {
            skippedReason = "Another content source was used";
          }
        }
        return <LogStepCard key={stepId} entry={entry} stepId={stepId} label={label} subtitle={subtitle} icon={icon} skippedReason={skippedReason}>{body}</LogStepCard>;
      })}
      <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider pt-2">Content Comparison</div>
      <ContentComparison
        left={article.content}
        right={article.contentClean}
        leftLabel={`Raw (${article.contentRawLength.toLocaleString()} chars)`}
        rightLabel={`Cleaned (${article.contentCleanLength.toLocaleString()} chars)`}
      />
    </div>
  );
}

function TranslatedDetail({ article, log }: { article: ArticleDetail; log: LogEntry[] }) {
  const contentLog = log.find((e) => e.step === "translate_content");
  const steps = STEP_MAP.translated;

  return (
    <div className="p-4 space-y-4">
      {steps.map((stepId) => {
        const entry = log.find((e) => e.step === stepId);
        const { label, icon } = STEP_DISPLAY[stepId] || { label: stepId, icon: Languages };
        let body: React.ReactNode = null;
        if (stepId === "detect_language" && entry) {
          const lang = (entry.detected || "unknown").toUpperCase();
          const LANG_NAMES: Record<string, string> = { AR: "Arabic", EN: "English", ES: "Spanish", FR: "French", DE: "German", TR: "Turkish", ZH: "Chinese" };
          const langName = LANG_NAMES[lang] || lang;
          const isArabic = entry.detected === "ar";
          body = (
            <span className={isArabic ? "text-success" : "text-primary"}>
              {isArabic
                ? "Original article is in Arabic — no translation needed"
                : `Original article is in ${langName} — translating to Arabic`}
            </span>
          );
        } else if (stepId === "translate_content" && entry) {
          body = (
            <>
              {entry.status === "ok" && entry.inputChars != null && entry.outputChars != null && (
                <span>{entry.inputChars.toLocaleString()} → {entry.outputChars.toLocaleString()} chars</span>
              )}
              {entry.status === "skipped" && <span>{entry.reason ?? "Skipped"}</span>}
              {entry.promptSent && <div className="mt-1"><ExpandableText label="prompt" text={entry.promptSent} maxLen={500} /></div>}
              {entry.rawResponse && <div className="mt-1"><ExpandableText label="response" text={entry.rawResponse} maxLen={500} /></div>}
            </>
          );
        } else if (stepId === "translate_analysis" && entry) {
          body = (
            <>
              {entry.status === "ok" && (entry as any).fieldsTranslated != null && <span>{(entry as any).fieldsTranslated} fields</span>}
              {entry.status === "skipped" && <span>{entry.reason ?? "Skipped"}</span>}
              {entry.promptSent && <div className="mt-1"><ExpandableText label="prompt" text={entry.promptSent} maxLen={400} /></div>}
              {entry.rawResponse && <div className="mt-1"><ExpandableText label="response" text={entry.rawResponse} maxLen={400} /></div>}
            </>
          );
        } else if (stepId === "translate_research" && entry) {
          body = (
            <>
              {entry.status === "ok" && entry.inputChars != null && entry.outputChars != null && (
                <span>{entry.inputChars.toLocaleString()} → {entry.outputChars.toLocaleString()} chars</span>
              )}
              {(entry.status === "skipped" || entry.status === "failed") && <span>{entry.reason ?? (entry as any).error ?? entry.status}</span>}
              {entry.promptSent && <div className="mt-1"><ExpandableText label="prompt" text={entry.promptSent} maxLen={400} /></div>}
            </>
          );
        }
        const { subtitle } = STEP_DISPLAY[stepId] || {};
        return <LogStepCard key={stepId} entry={entry ?? null} stepId={stepId} label={label} subtitle={subtitle} icon={icon}>{body}</LogStepCard>;
      })}

      {article.analysis && (article.analysis.topicAr || article.analysis.summaryAr || article.analysis.tagsAr?.length || article.analysis.regionAr || article.analysis.uniqueAngleAr) && (
        <ResultCard label="Arabic Output" icon={Languages}>
          {article.analysis.topicAr && <div className="mb-2"><div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1">Topic</div><div className="text-[11px]" dir="rtl">{article.analysis.topicAr}</div></div>}
          {article.analysis.summaryAr && <div className="mb-2"><div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1">Summary</div><div className="text-[11px]" dir="rtl">{article.analysis.summaryAr}</div></div>}
          {article.analysis.tagsAr && article.analysis.tagsAr.length > 0 && (
            <div className="mb-2">
              <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1">Tags</div>
              <div className="flex flex-wrap gap-1.5" dir="rtl">{article.analysis.tagsAr.map((t, i) => <span key={i} className="px-2 py-0.5 rounded bg-primary/10 text-primary text-[10px] font-mono">{t}</span>)}</div>
            </div>
          )}
          {article.analysis.regionAr && <div className="mb-2"><div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1">Region</div><div className="text-[11px]" dir="rtl">{article.analysis.regionAr}</div></div>}
          {article.analysis.uniqueAngleAr && <div><div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1">Unique Angle</div><div className="text-[11px] italic" dir="rtl">{article.analysis.uniqueAngleAr}</div></div>}
        </ResultCard>
      )}

      {/* Content comparison */}
      {contentLog?.status === "ok" && (
        <>
          <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider">Translation Comparison</div>
          <ContentComparison
            left={article.contentClean}
            right={article.contentAr}
            leftLabel={`Original (${article.contentCleanLength.toLocaleString()} chars)`}
            rightLabel={`Arabic Translation (${article.contentArLength.toLocaleString()} chars)`}
            rightDir="rtl"
          />
        </>
      )}

      {contentLog?.status === "skipped" && article.contentAr && (
        <ContentBlock
          label={`Arabic Content (${article.contentArLength.toLocaleString()} chars)`}
          content={article.contentAr}
          dir="rtl"
        />
      )}
    </div>
  );
}

function AiAnalysisDetail({ article, log }: { article: ArticleDetail; log: LogEntry[] }) {
  const classifyLog = log.find((e) => e.step === "classify");
  const analysis = article.analysis;

  if (!analysis) {
    return <EmptyState icon={Brain} title="No classification data yet" />;
  }

  if (analysis.parseError) {
    return (
      <div className="p-4 space-y-3">
        <StatusBadge status="failed" label="Parse Error" />
        {analysis.raw && <ContentBlock label="Raw AI Response (failed to parse)" content={analysis.raw} />}
      </div>
    );
  }

  const stepId = "classify";
  const { label, icon } = STEP_DISPLAY[stepId] || { label: "Classification", icon: Brain };

  return (
    <div className="p-4 space-y-4">
      <LogStepCard entry={classifyLog ?? null} stepId={stepId} label={label} subtitle={STEP_DISPLAY[stepId]?.subtitle} icon={icon}>
        {classifyLog?.quality && <QualityBadge quality={classifyLog.quality} />}
        {classifyLog?.inputChars != null && <span>{classifyLog.inputChars.toLocaleString()} chars → {classifyLog.service ?? "Claude Haiku"}</span>}
        {classifyLog?.promptSent && <div className="mt-1"><ExpandableText label="prompt" text={classifyLog.promptSent} maxLen={800} /></div>}
        {classifyLog?.rawResponse && <div className="mt-1"><ExpandableText label="response" text={classifyLog.rawResponse} maxLen={800} /></div>}
      </LogStepCard>

      <ResultCard label="Classification Results" icon={Brain}>
        {analysis.topic && (
          <div className="mb-2">
            <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1">Topic (original language)</div>
            <div className="text-[13px] text-foreground font-medium leading-relaxed" dir="auto">{analysis.topic}</div>
          </div>
        )}
        {analysis.summary && (
          <div className="mb-2">
            <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1">Summary (original language)</div>
            <div className="text-[12px] text-foreground/80 leading-relaxed" dir="auto">{analysis.summary}</div>
          </div>
        )}
        {analysis.tags && analysis.tags.length > 0 && (
          <div className="mb-2">
            <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-2">Tags (original language)</div>
            <div className="flex flex-wrap gap-1.5" dir="auto">
              {analysis.tags.map((tag, i) => (
                <span key={i} className="px-2.5 py-1 rounded-full bg-primary/10 text-primary text-[11px] font-mono">{tag}</span>
              ))}
            </div>
          </div>
        )}
        {analysis.region && <InfoCard label="Region (original language)" value={analysis.region} />}
        <div className="grid grid-cols-2 gap-3 max-sm:grid-cols-1">
          <InfoCard label="Content Type" value={analysis.contentType || "—"} />
        </div>
        {analysis.uniqueAngle && (
          <div>
            <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-1">Unique Angle (original language)</div>
            <div className="text-[12px] text-foreground/80 italic" dir="auto">{analysis.uniqueAngle}</div>
          </div>
        )}
      </ResultCard>
    </div>
  );
}

function ScoringDetail({ article, log }: { article: ArticleDetail; log: LogEntry[] }) {
  const stepLog = getStepLogs("score", log);
  const hasAny = stepLog.length > 0;
  if (!hasAny) {
    return <EmptyState icon={Sparkles} title="No scoring data yet" />;
  }

  const scoreLog = stepLog.find((e) => e.step === "score");
  const relevance = scoreLog?.relevance ?? 0;
  const viral = scoreLog?.viralPotential ?? 0;
  const freshness = scoreLog?.freshness ?? 0;
  const prefBias = scoreLog?.preferenceBias ?? 0;
  const competitionPenalty = scoreLog?.competitionPenalty ?? 0;
  const finalScore = scoreLog?.finalScore ?? 0;

  return (
    <div className="p-4 space-y-4">
      {stepLog.map((entry) => {
        const stepId = entry.step;
        const hasDisplay = entry.display && Array.isArray(entry.display) && entry.display.length > 0;
        const displayInfo = STEP_DISPLAY[stepId];
        const entryLabel = entry.label ?? displayInfo?.label ?? stepId;
        const entrySubtitle = entry.subtitle ?? displayInfo?.subtitle;
        const entryIcon = entry.icon ? resolveIcon(entry.icon) : (displayInfo?.icon ?? Sparkles);

        let body: React.ReactNode = null;

        if (hasDisplay) {
          body = <DisplayBlockList blocks={entry.display!} />;
        } else if (stepId === "score_similarity") {
          body = (
            <>
              {entry.status === "ok" && (
                <>
                  <span>{(entry as any).embeddingInputChars?.toLocaleString()} chars → {(entry as any).matchCount ?? 0} matches</span>
                  {(entry as any).similarVideos?.length > 0 && (
                    <ul className="list-disc list-inside text-[11px] mt-1 space-y-0.5">
                      {((entry as any).similarVideos as { title?: string; similarity?: number }[]).slice(0, 5).map((v, i) => (
                        <li key={i}>{v.title || "—"} ({(v.similarity ?? 0).toFixed(2)})</li>
                      ))}
                    </ul>
                  )}
                </>
              )}
              {entry.status !== "ok" && <span>{entry.reason || entry.error || "Skipped"}</span>}
            </>
          );
        } else if (stepId === "score_topic_demand") {
          body = (
            <>
              {entry.status === "ok" && (
                <>
                  <ScoreGauge label="Topic Demand" value={entry.topicDemand ?? 0} />
                  <div className="flex items-center gap-3 text-[11px] mt-1">
                    <span className="text-muted-foreground">{entry.similarCount ?? 0} competitor videos analysed</span>
                    {entry.avgPerformanceRatio != null && (
                      <span className="text-muted-foreground">Avg {entry.avgPerformanceRatio}× channel average</span>
                    )}
                  </div>
                </>
              )}
              {entry.status !== "ok" && <span className="text-muted-foreground">{entry.reason || entry.error || "Skipped"}</span>}
            </>
          );
        } else if (stepId === "score_niche") {
          body = (
            <>
              {entry.status === "ok" && (
                <ScoreGauge label="Niche Score" value={entry.nicheScore ?? 0} />
              )}
              {entry.status !== "ok" && <span className="text-muted-foreground">{entry.reason || entry.error || "Skipped"}</span>}
            </>
          );
        } else if (stepId === "score_ai_analysis") {
          body = (
            <>
              {entry.sentiment && <span>Sentiment: {entry.sentiment}</span>}
              {entry.viralPotential != null && <span className="ml-2">Viral: {entry.viralPotential}</span>}
              {entry.relevance != null && <span className="ml-2">Relevance: {entry.relevance}</span>}
              {entry.promptSent && <div className="mt-1"><ExpandableText label="prompt" text={entry.promptSent} maxLen={500} /></div>}
              {entry.rawResponse && <div className="mt-1"><ExpandableText label="response" text={entry.rawResponse} maxLen={500} /></div>}
            </>
          );
        } else if (stepId === "score") {
          const rawScore = relevance * 0.35 + viral * 0.30 + freshness * 0.35;
          const weighted = rawScore * 0.60;
          const biasContrib = prefBias * 0.40;
          const compositeOut10 = (Math.round(finalScore * 10 * 10) / 10).toFixed(1);
          body = (
            <>
              <div className="space-y-1">
                <ScoreRow label="Relevance" value={relevance} weight={0.35} result={relevance * 0.35} />
                <ScoreRow label="Viral" value={viral} weight={0.30} result={viral * 0.30} />
                <ScoreRow label="Freshness" value={freshness} weight={0.35} result={freshness * 0.35} />
              </div>
              <div className="text-[11px] font-mono mt-2 space-y-1">
                <div className="text-muted-foreground">
                  Weighted sum = {rawScore.toFixed(3)}
                </div>
                <div className="text-muted-foreground">
                  {rawScore.toFixed(3)} × 0.60 = {weighted.toFixed(3)}
                  {prefBias !== 0 && <>{" + "}{prefBias.toFixed(2)} × 0.40 = {(weighted + biasContrib).toFixed(3)}</>}
                  {competitionPenalty > 0 && <>{" − "}{competitionPenalty.toFixed(2)} = {(weighted + biasContrib - competitionPenalty).toFixed(3)}</>}
                </div>
                <div>
                  {"→ "}<span className="font-bold text-success">Final {finalScore.toFixed(2)}</span>
                </div>
                <div className="pt-1 border-t border-border mt-1">
                  {finalScore.toFixed(2)} × 10 = <span className="font-bold text-foreground">{compositeOut10}/10</span>
                </div>
              </div>
            </>
          );
        } else {
          body = (
            <>
              {entry.status !== "ok" && entry.reason && <span className="text-muted-foreground">{entry.reason}</span>}
              {entry.error && <span className="text-destructive">{entry.error}</span>}
            </>
          );
        }

        return (
          <LogStepCard
            key={stepId}
            entry={entry}
            stepId={stepId}
            label={entryLabel}
            subtitle={entrySubtitle}
            icon={entryIcon}
          >
            {body}
          </LogStepCard>
        );
      })}

      {article.rankReason && (
        <ResultCard label="Score Rationale" icon={Sparkles}>
          <div className="flex flex-wrap gap-1.5">
            {article.rankReason.split(", ").map((reason, i) => (
              <span key={i} className="px-2 py-0.5 rounded-full bg-primary/10 text-primary text-[10px] font-mono">
                {reason}
              </span>
            ))}
          </div>
        </ResultCard>
      )}

      {(() => {
        const brief = (article.analysis as Analysis | null)?.research?.brief;
        if (!brief?.competitionInsight) return null;
        return (
          <ResultCard label="Competition Insight" icon={Target}>
            <div className="text-[12px] text-foreground/85 leading-relaxed" dir="auto">{brief.competitionInsight}</div>
          </ResultCard>
        );
      })()}
    </div>
  );
}

/* ─── Synthesis Detail (AI synthesis → Research complete + structured brief) ─── */

function SynthesisDetail({ article, log }: { article: ArticleDetail; log: LogEntry[] }) {
  const research = (article.analysis as Analysis | null)?.research;
  const brief = research?.brief;
  const steps = STEP_MAP.synthesis;

  return (
    <div className="p-4 space-y-4">
      {steps.map((stepId) => {
        const entry = log.find((e) => e.step === stepId);
        const { label, icon } = STEP_DISPLAY[stepId] || { label: stepId, icon: Search };
        let body: React.ReactNode = null;
        if (stepId === "synthesis" && entry) {
          body = (
            <>
              {(entry as any).briefKeys?.length > 0 && <span>{(entry as any).briefKeys.length} sections</span>}
              {entry.promptSent && <div className="mt-1"><ExpandableText label="prompt" text={entry.promptSent} maxLen={400} /></div>}
              {entry.rawResponse && <div className="mt-1"><ExpandableText label="response" text={entry.rawResponse} maxLen={400} /></div>}
            </>
          );
        } else if (stepId === "research" && entry) {
          body = (
            <>
              {entry.status && <span>{entry.status === "ok" ? "Research complete" : entry.status === "partial" ? "Partially researched" : entry.status}</span>}
              {(entry.narrativeStrength != null || brief?.narrativeStrength != null) && (
                <span className="ml-2 font-semibold text-success">Narrative: {(brief?.narrativeStrength ?? entry.narrativeStrength ?? 0)}/10</span>
              )}
            </>
          );
        }
        const decision = log.find((e) => e.step === "research_decision");
        const skippedReason = !entry && decision && !decision.needed ? "Research not needed" : undefined;
        const { subtitle } = STEP_DISPLAY[stepId] || {};
        return <LogStepCard key={stepId} entry={entry ?? null} stepId={stepId} label={label} subtitle={subtitle} icon={icon} skippedReason={skippedReason}>{body}</LogStepCard>;
      })}

      {brief?.suggestedHook && (
        <ResultCard label="Video Hook" icon={Sparkles}>
          <div className="text-[14px] text-foreground font-medium leading-relaxed" dir="auto">"{brief.suggestedHook}"</div>
        </ResultCard>
      )}
      {(brief?.whatHappened || brief?.howItHappened || brief?.whatWasTheResult) && (
        <ResultCard label="Core Narrative" icon={FileText}>
          <div className="space-y-3">
            {brief?.whatHappened && (
              <div>
                <div className="text-[10px] font-mono text-primary uppercase tracking-wider mb-1.5">What happened?</div>
                <div className="text-[13px] text-foreground/90 leading-[1.8]" dir="auto">{brief.whatHappened}</div>
              </div>
            )}
            {brief?.howItHappened && (
              <div>
                <div className="text-[10px] font-mono text-orange uppercase tracking-wider mb-1.5">How did it happen?</div>
                <div className="text-[13px] text-foreground/90 leading-[1.8]" dir="auto">{brief.howItHappened}</div>
              </div>
            )}
            {brief?.whatWasTheResult && (
              <div>
                <div className="text-[10px] font-mono text-success uppercase tracking-wider mb-1.5">What was the result?</div>
                <div className="text-[13px] text-foreground/90 leading-[1.8]" dir="auto">{brief.whatWasTheResult}</div>
              </div>
            )}
          </div>
        </ResultCard>
      )}
      {brief?.keyFacts && brief.keyFacts.length > 0 && (
        <ResultCard label="Key Facts" icon={ListOrdered}>
          <div className="space-y-1.5">
            {brief.keyFacts.map((fact, i) => (
              <div key={i} className="flex items-start gap-2 px-3 py-2 rounded-lg bg-card/50 border border-border">
                <span className="text-[10px] font-mono text-purple font-bold mt-0.5 shrink-0">{i + 1}</span>
                <span className="text-[12px] text-foreground/85 leading-relaxed" dir="auto">{fact}</span>
              </div>
            ))}
          </div>
        </ResultCard>
      )}
      {brief?.timeline && brief.timeline.length > 0 && (
        <ResultCard label="Timeline" icon={ListOrdered}>
          <div className="space-y-1">
            {brief.timeline.map((entry, i) => (
              <div key={i} className="flex items-start gap-3 px-3 py-2 rounded-lg bg-card/50 border border-border">
                <span className="text-[11px] font-mono text-primary shrink-0 w-24">{entry.date}</span>
                <span className="text-[12px] text-foreground/85 leading-relaxed" dir="auto">{entry.event}</span>
              </div>
            ))}
          </div>
        </ResultCard>
      )}
      {brief?.mainCharacters && brief.mainCharacters.length > 0 && (
        <ResultCard label="Key People" icon={Users}>
          <div className="grid grid-cols-2 gap-2 max-sm:grid-cols-1">
            {brief.mainCharacters.map((person, i) => (
              <div key={i} className="px-3 py-2.5 rounded-lg bg-card/50 border border-border">
                <div className="text-[12px] font-semibold text-foreground" dir="auto">{person.name}</div>
                <div className="text-[11px] text-muted-foreground mt-0.5" dir="auto">{person.role}</div>
              </div>
            ))}
          </div>
        </ResultCard>
      )}
      {brief?.sources && brief.sources.length > 0 && (
        <ResultCard label="Sources" icon={Link2}>
          <div className="flex flex-wrap gap-1.5">
            {brief.sources.map((s, i) => (
              s.url ? (
                <a key={i} href={s.url} target="_blank" rel="noopener noreferrer"
                  className="px-2 py-1 rounded bg-primary/10 text-primary text-[10px] font-mono hover:bg-primary/20 transition-colors">
                  {s.title || s.url}
                </a>
              ) : (
                <span key={i} className="px-2 py-1 rounded bg-dim/10 text-muted-foreground text-[10px] font-mono">{s.title}</span>
              )
            ))}
          </div>
        </ResultCard>
      )}
    </div>
  );
}

function ScriptDetail({ article, log }: { article: ArticleDetail; log: LogEntry[] }) {
  const entry = log.find((e) => e.step === "auto_script");
  const { label, icon, subtitle } = STEP_DISPLAY.auto_script || { label: "Draft Script", icon: PenLine };
  const draftScript = (article.analysis as Analysis | null)?.draftScript as Record<string, unknown> | undefined;

  return (
    <div className="p-4 space-y-3">
      <LogStepCard entry={entry ?? null} stepId="auto_script" label={label} subtitle={subtitle} icon={icon}>
        {entry?.status === "ok" && (
          <div className="space-y-1 text-[12px]">
            <span className="text-success">Draft script generated</span>
            {entry.dialect && <span className="text-muted-foreground"> · Dialect: {entry.dialect}</span>}
            {entry.hasHooks && <span className="text-muted-foreground"> · Branded hooks included</span>}
            {entry.hasResearch && <span className="text-muted-foreground"> · Research context included</span>}
          </div>
        )}
        {entry?.status === "skipped" && <span className="text-muted-foreground">{entry.reason ?? "Skipped"}</span>}
        {entry?.status === "partial" && <span className="text-orange">{entry.error ?? "Generation failed (non-blocking)"}</span>}
      </LogStepCard>

      {draftScript?.suggestedTitle && (
        <ResultCard label="Suggested Title">
          <p className="text-sm font-medium" dir="rtl" style={{ textAlign: "right" }}>{String(draftScript.suggestedTitle)}</p>
        </ResultCard>
      )}
      {draftScript?.script && (
        <ResultCard label="Script" icon={PenLine}>
          <pre className="text-[12px] whitespace-pre-wrap leading-relaxed text-foreground/80 max-h-[400px] overflow-y-auto" dir="rtl" style={{ textAlign: "right" }}>
            {String(draftScript.script)}
          </pre>
        </ResultCard>
      )}
      {Array.isArray(draftScript?.youtubeTags) && (draftScript.youtubeTags as string[]).length > 0 && (
        <ResultCard label="YouTube Tags">
          <div className="flex flex-wrap gap-1.5">
            {(draftScript.youtubeTags as string[]).map((tag, i) => (
              <span key={i} className="px-2 py-0.5 rounded-full bg-card border border-border text-[11px]">{tag}</span>
            ))}
          </div>
        </ResultCard>
      )}
    </div>
  );
}

function PromoteDetail({ article, log, pp }: { article: ArticleDetail; log: LogEntry[]; pp: (p: string) => string }) {
  const entry = log.find((e) => e.step === "promote");
  const { label, icon } = STEP_DISPLAY.promote || { label: "Story Promotion", icon: CheckCircle2 };

  return (
    <div className="p-4 space-y-3">
      <LogStepCard
        entry={entry ?? null}
        stepId="promote"
        label={entry?.status === "created" ? "Story Created" : entry?.status === "linked" ? "Linked to Existing" : label}
        subtitle={STEP_DISPLAY.promote?.subtitle}
        icon={icon}
      >
        {entry?.status === "created" && article.storyId && (
          <Link to={pp(`/story/${article.storyId}`)} className="text-success hover:underline font-medium">
            Story created — click to view
          </Link>
        )}
        {entry?.status === "linked" && <span>Article linked to existing story (same headline).</span>}
        {entry?.status === "skipped" && <span>{entry.reason ?? "Skipped"}</span>}
        {entry?.status === "failed" && <span className="text-destructive">{entry.error ?? "Failed"}</span>}
      </LogStepCard>
      {entry?.status === "created" && article.storyId && (
        <Link to={pp(`/story/${article.storyId}`)}
          className="flex items-center gap-2 px-4 py-3 rounded-lg bg-success/5 border border-success/20 hover:bg-success/10 transition-colors">
          <CheckCircle2 className="w-4 h-4 text-success" />
          <span className="text-[13px] font-semibold">View story</span>
          <ArrowLeft className="w-4 h-4 text-muted-foreground ml-auto rotate-180" />
        </Link>
      )}
    </div>
  );
}

/* ─── Research Detail ─── */

function ResearchDetail({ article, log, pp }: { article: ArticleDetail; log: LogEntry[]; pp: (p: string) => string }) {
  const research = (article.analysis as Analysis | null)?.research;
  const steps = STEP_MAP.research;

  return (
    <div className="p-4 space-y-4">
      {/* Stage-by-stage cards (same order as Kanban) */}
      {steps.map((stepId) => {
        const entry = log.find((e) => e.step === stepId);
        const { label, icon } = STEP_DISPLAY[stepId] || { label: stepId, icon: Search };
        let body: React.ReactNode = null;
        if (stepId === "research_decision" && entry) {
          body = <>{entry.reason ?? (entry.needed ? "Research needed" : "Skipped")}</>;
        } else if (stepId === "firecrawl_search" && entry) {
          body = (
            <>
              {entry.reason && <span>{entry.reason}</span>}
              {entry.query && <div className="mt-1 font-mono text-[11px]">Query: {entry.query}</div>}
              {entry.resultsCount != null && <div className="mt-1">{entry.resultsCount} results</div>}
              {entry.titles?.slice(0, 3).map((t: string, i: number) => <div key={i} className="text-[11px] truncate">· {t}</div>)}
            </>
          );
        } else if (stepId === "perplexity_context" && entry) {
          body = (
            <>
              {entry.chars != null && <span>{entry.chars.toLocaleString()} chars</span>}
              {entry.citations != null && <span> · {entry.citations} citations</span>}
              {entry.promptSent && <div className="mt-1"><ExpandableText label="prompt" text={entry.promptSent} maxLen={500} /></div>}
              {entry.rawResponse && <div className="mt-1"><ExpandableText label="response" text={entry.rawResponse} maxLen={500} /></div>}
            </>
          );
        }
        let skippedReason: string | undefined;
        if (!entry && stepId !== "research_decision") {
          const decision = log.find((e) => e.step === "research_decision");
          if (decision && !decision.needed) skippedReason = "Research not needed";
        }
        const { subtitle } = STEP_DISPLAY[stepId] || {};
        return <LogStepCard key={stepId} entry={entry ?? null} stepId={stepId} label={label} subtitle={subtitle} icon={icon} skippedReason={skippedReason}>{body}</LogStepCard>;
      })}

      {research?.relatedArticles && research.relatedArticles.length > 0 && (
        <ResultCard label="Related Articles" icon={Search}>
          <div className="space-y-1.5">
            {research.relatedArticles.map((ra, i) => (
              <div key={i} className="px-3 py-2.5 rounded-lg bg-card/50 border border-border">
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-[10px] font-mono text-primary shrink-0">{i + 1}.</span>
                  {ra.url ? (
                    <a href={ra.url} target="_blank" rel="noopener noreferrer"
                      className="text-[12px] font-medium text-foreground hover:text-primary transition-colors truncate">
                      {ra.title || ra.url}
                    </a>
                  ) : (
                    <span className="text-[12px] font-medium text-foreground truncate">{ra.title}</span>
                  )}
                </div>
                {ra.snippet && (
                  <div className="text-[11px] text-muted-foreground line-clamp-2 pl-5">{ra.snippet}</div>
                )}
              </div>
            ))}
          </div>
        </ResultCard>
      )}

      {research?.backgroundContext && (
        <ResultCard label="Background Context" icon={Brain}>
          <ContentBlock
            label={`Perplexity (${research.backgroundContext.length.toLocaleString()} chars)`}
            content={research.backgroundContext}
            dir="auto"
          />
        </ResultCard>
      )}

      {research?.similarVideos && research.similarVideos.length > 0 && (
        <ResultCard label="Similar Competition Videos" icon={Target}>
          <div className="space-y-1.5">
            {research.similarVideos.map((v, i) => (
              <div key={i} className="flex items-center gap-3 px-3 py-2 rounded-lg bg-card/50 border border-border">
                <span className="text-[10px] font-mono text-purple shrink-0">{i + 1}.</span>
                <span className="text-[12px] text-foreground truncate flex-1" dir="auto">{v.title}</span>
                <div className="flex items-center gap-2 text-[10px] font-mono text-muted-foreground shrink-0">
                  {v.views != null && <span>{v.views.toLocaleString()} views</span>}
                  {v.channel && <span>{v.channel}</span>}
                  {v.similarity != null && (
                    <span className="text-purple">{Math.round(v.similarity * 100)}% match</span>
                  )}
                </div>
              </div>
            ))}
          </div>
        </ResultCard>
      )}
    </div>
  );
}

/* ─── Small helpers ─── */

function InfoCard({ label, value, color, dir }: { label: string; value: string; color?: string; dir?: string }) {
  return (
    <div className="px-3 py-2.5 rounded-lg bg-card/50 border border-border">
      <div className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider mb-0.5">{label}</div>
      <div className={`text-[13px] font-medium ${color || "text-foreground"}`} dir={dir}>{value}</div>
    </div>
  );
}

function ScoreGauge({ label, value }: { label: string; value?: number }) {
  const v = typeof value === "number" ? value : 0;
  const pct = Math.round(v * 100);
  const color = pct >= 70 ? "text-success" : pct >= 40 ? "text-orange" : "text-destructive";
  const bgColor = pct >= 70 ? "bg-success" : pct >= 40 ? "bg-orange" : "bg-destructive";

  return (
    <div className="px-3 py-2.5 rounded-lg bg-card/50 border border-border">
      <div className="flex items-center justify-between mb-1">
        <span className="text-[10px] font-mono text-muted-foreground uppercase tracking-wider">{label}</span>
        <span className={`text-[13px] font-mono font-bold ${color}`}>{v.toFixed(2)}</span>
      </div>
      <div className="w-full h-1.5 bg-border rounded-full overflow-hidden">
        <div className={`h-full rounded-full ${bgColor}`} style={{ width: `${pct}%` }} />
      </div>
    </div>
  );
}

function ScoreRow({ label, value, weight, result }: { label: string; value: number; weight: number; result: number }) {
  const pct = Math.round(value * 100);
  return (
    <div className="flex items-center gap-3 px-3 py-2 rounded-lg bg-card/50 border border-border">
      <span className="text-[12px] font-mono text-muted-foreground w-28">{label}</span>
      <div className="flex-1 h-1.5 bg-border rounded-full overflow-hidden">
        <div className="h-full rounded-full bg-primary" style={{ width: `${pct}%` }} />
      </div>
      <span className="text-[11px] font-mono text-foreground w-10 text-right">{value.toFixed(2)}</span>
      <span className="text-[10px] font-mono text-muted-foreground">× {weight}</span>
      <span className="text-[11px] font-mono text-foreground w-12 text-right">= {result.toFixed(3)}</span>
    </div>
  );
}
